// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace JusticeLeague.Client.Models {
    public enum Superpower {
        [EnumMember(Value = "SuperStrength")]
        SuperStrength,
        [EnumMember(Value = "Flight")]
        Flight,
        [EnumMember(Value = "SuperSpeed")]
        SuperSpeed,
    }
}
